apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  namespace: homelab
  labels:
    app: nginx-blue
spec:
  selector:
    matchLabels:
      app: nginx-blue
  replicas: 3

  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      containers:
        - name: nginx-blue
          image: nginx:latest
          ports:
            - containerPort: 80
              name: nginx-blue

          volumeMounts:
            - name: nginx-blue-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-blue-html
          configMap:
            name: nginx-blue-cm
