apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: monitoring-cert
  namespace: monitoring

spec:
  secretName: monitoring-tls-secret

  commonName: monitoring.homelab.local

  dnsNames:
    - monitoring.homelab.local

  issuerRef:
    name: homelab-cluster-ca
    kind: ClusterIssuer
