apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata:
  name: developer-read-role
  namespace: developer-space


rules:

- apiGroups:
    - ""

  resources: # wht the SA can access
    - pods
    - services

  verbs:
    - get # read a pod 
    - list # list all pods
    - watch # watch for changes in pods // moniter it
 

- apiGroups:
    - apps

  resources:
    - deployments

  verbs:
    - get
    - list
    - watch