apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: nginx-blue-only-reader
  namespace: homelab

rules:
  - apiGroups:
      - "app"

    resources:
      - deployment

    verbs:
      - get
      - update
      - patch

  - apiGroups:
      - ""

    resources:
      - pods

    verbs:
      - get
      - list
